"""Collect port activity, port reference data, trade nowcasts, and disruption
events from IMF PortWatch.

Complements `imf_portwatch` (chokepoints) using the same public ArcGIS services
behind portwatch.imf.org. No key required.

IMF terms of use allow redistribution free of charge with attribution
("Source: International Monetary Fund, PortWatch"); disruption events originate
from GDACS and carry its attribution too.
"""
from __future__ import annotations

import json
import logging
import re
import tempfile
from datetime import UTC, date, datetime, timedelta
from pathlib import Path
from typing import Any

import duckdb
import polars as pl
import requests

from src.collectors.http_utils import get_with_retry
from src.config import settings
from src.storage.tracker import SourceTracker, TimedCollector
from src.storage.writer import get_connection, write_raw

logger = logging.getLogger(__name__)

BASE_URL = "https://services9.arcgis.com/weJ1QsnbMYJlCHdG/arcgis/rest/services"

DAILY_PORTS_URL = f"{BASE_URL}/Daily_Ports_Data/FeatureServer/0/query"
PORTS_URL = f"{BASE_URL}/PortWatch_ports_database/FeatureServer/0/query"
TRADENOW_URL = f"{BASE_URL}/Monthly_TradeNow/FeatureServer/0/query"
DISRUPTIONS_URL = f"{BASE_URL}/portwatch_disruptions_database/FeatureServer/0/query"
GEOPULSE_URL = f"{BASE_URL}/geopulse_events/FeatureServer/0/query"

#: The whole Daily_Ports_Data layer as one CSV, generated by ArcGIS Hub.
#: Paging the full ~6M rows through the query API takes ~2 hours; this takes
#: minutes. It can lag the live layer, so the API tops it up afterwards.
DAILY_PORTS_CSV_URL = (
    "https://portwatch.imf.org/api/download/v1/items/"
    "83b1bbc7b3354c5fb1f40673bb8f852e/csv?layers=0"
)

SOURCE_ACTIVITY = "imf_portwatch_port_activity"
SOURCE_PROFILES = "imf_portwatch_port_profiles"
SOURCE_TRADENOW = "imf_portwatch_tradenow"
SOURCE_DISRUPTIONS = "imf_portwatch_disruptions"
SOURCE_GEOPULSE = "imf_portwatch_geopulse"

PAGE_SIZE = 1000  # the layers' maxRecordCount

#: PortWatch revises recent days as late AIS data arrives, so each run
#: re-fetches this many days before the latest stored date.
REVISION_WINDOW_DAYS = 30
#: History pulled on a first run when bulk backfill is not allowed.
INITIAL_LOOKBACK_DAYS = 90

# (target column, PortWatch field, dtype)
_ACTIVITY_FIELDS: list[tuple[str, str, pl.DataType]] = [
    ("port_id", "portid", pl.Utf8()),
    ("port_name", "portname", pl.Utf8()),
    ("country", "country", pl.Utf8()),
    ("iso3", "ISO3", pl.Utf8()),
    *[
        (f"portcalls_{v}", f"portcalls_{v}", pl.Int32())
        for v in ("container", "dry_bulk", "general_cargo", "roro", "tanker", "cargo")
    ],
    ("portcalls", "portcalls", pl.Int32()),
    *[
        (f"{flow}_{v}", f"{flow}_{v}", pl.Float64())
        for flow in ("import", "export")
        for v in ("container", "dry_bulk", "general_cargo", "roro", "tanker", "cargo")
    ],
    ("import_total", "import", pl.Float64()),
    ("export_total", "export", pl.Float64()),
]

_PROFILE_FIELDS: list[tuple[str, str, pl.DataType]] = [
    ("port_id", "portid", pl.Utf8()),
    ("port_name", "portname", pl.Utf8()),
    ("full_name", "fullname", pl.Utf8()),
    ("country", "country", pl.Utf8()),
    ("iso3", "ISO3", pl.Utf8()),
    ("continent", "continent", pl.Utf8()),
    ("locode", "LOCODE", pl.Utf8()),
    ("latitude", "lat", pl.Float64()),
    ("longitude", "lon", pl.Float64()),
    ("vessel_count_total", "vessel_count_total", pl.Int32()),
    ("vessel_count_container", "vessel_count_container", pl.Int32()),
    ("vessel_count_dry_bulk", "vessel_count_dry_bulk", pl.Int32()),
    ("vessel_count_general_cargo", "vessel_count_general_cargo", pl.Int32()),
    ("vessel_count_roro", "vessel_count_RoRo", pl.Int32()),
    ("vessel_count_tanker", "vessel_count_tanker", pl.Int32()),
    ("industry_top1", "industry_top1", pl.Utf8()),
    ("industry_top2", "industry_top2", pl.Utf8()),
    ("industry_top3", "industry_top3", pl.Utf8()),
    ("share_country_maritime_import", "share_country_maritime_import", pl.Float64()),
    ("share_country_maritime_export", "share_country_maritime_export", pl.Float64()),
]

_TRADENOW_NUMERIC = [
    *[
        f"ais_portcalls_{v}"
        for v in ("container", "general_cargo", "dry_bulk", "roro", "tanker")
    ],
    *[
        f"ais_{flow}_{v}"
        for v in ("tanker", "dry_bulk", "container", "general_cargo", "roro")
        for flow in ("import", "export")
    ],
    "value_import_total",
    "value_export_total",
    "volume_import_total",
    "volume_export_total",
    "trade_value",
    "trade_volume",
]
_TRADENOW_FIELDS: list[tuple[str, str, pl.DataType]] = [
    ("region", "region", pl.Utf8()),
    ("iso3", "ISO3", pl.Utf8()),
    *[(c, c, pl.Float64()) for c in _TRADENOW_NUMERIC],
]

_EVENT_SCHEMA: dict[str, pl.DataType] = {
    "event_id": pl.Utf8(),
    "episode_id": pl.Utf8(),
    "event_type": pl.Utf8(),
    "event_name": pl.Utf8(),
    "description": pl.Utf8(),
    "alert_level": pl.Utf8(),
    "alert_score": pl.Float64(),
    "severity_text": pl.Utf8(),
    "country": pl.Utf8(),
    "iso3": pl.Utf8(),
    "affected_countries": pl.Utf8(),
    "affected_ports": pl.Utf8(),
    "n_affected_ports": pl.Int32(),
    "affected_population": pl.Utf8(),
    "is_current": pl.Boolean(),
    "from_date": pl.Datetime("us"),
    "to_date": pl.Datetime("us"),
    "latitude": pl.Float64(),
    "longitude": pl.Float64(),
}


# ── ArcGIS helpers ────────────────────────────────────────────────────────


def query_all(
    url: str,
    where: str = "1=1",
    return_geometry: bool = False,
) -> list[dict[str, Any]]:
    """Page through an ArcGIS layer query and return every feature.

    Ordered by ObjectId so pages are stable -- without an explicit order the
    server may return overlapping or skipped rows across offsets.
    """
    features: list[dict[str, Any]] = []
    offset = 0
    while True:
        params: dict[str, Any] = {
            "where": where,
            "outFields": "*",
            "returnGeometry": "true" if return_geometry else "false",
            "outSR": "4326",
            "orderByFields": "ObjectId",
            "resultOffset": offset,
            "resultRecordCount": PAGE_SIZE,
            "f": "json",
        }
        data = get_with_retry(url, params=params, timeout=90, source="imf_portwatch").json()
        # ArcGIS reports query errors as HTTP 200 with an "error" body.
        if "error" in data:
            raise RuntimeError(f"ArcGIS query failed for {url}: {data['error']}")
        page = data.get("features", [])
        features.extend(page)
        if not page or not data.get("exceededTransferLimit"):
            break
        offset += len(page)
    return features


def _to_date(value: Any) -> date | None:
    """Parse an ArcGIS date: epoch ms, 'YYYY-MM-DD', or 'YYYY/MM/DD'."""
    if value is None or value == "":
        return None
    if isinstance(value, (int, float)):
        return datetime.fromtimestamp(value / 1000, tz=UTC).date()
    try:
        return date.fromisoformat(str(value)[:10].replace("/", "-"))
    except ValueError:
        return None


def _to_datetime(value: Any) -> datetime | None:
    """Parse an ArcGIS timestamp (epoch ms or ISO-8601) to naive UTC."""
    if value is None or value == "":
        return None
    if isinstance(value, (int, float)):
        return datetime.fromtimestamp(value / 1000, tz=UTC).replace(tzinfo=None)
    try:
        parsed = datetime.fromisoformat(str(value))
    except ValueError:
        return None
    if parsed.tzinfo is not None:
        parsed = parsed.astimezone(UTC).replace(tzinfo=None)
    return parsed


def _strip_html(value: Any) -> str | None:
    if not value:
        return None
    text = re.sub(r"<[^>]+>", " ", str(value))
    return re.sub(r"\s+", " ", text).strip() or None


def _map_fields(
    features: list[dict[str, Any]],
    fields: list[tuple[str, str, pl.DataType]],
) -> list[dict[str, Any]]:
    return [
        {target: feat.get("attributes", {}).get(src) for target, src, _ in fields}
        for feat in features
    ]


def _frame(rows: list[dict[str, Any]], schema: dict[str, pl.DataType]) -> pl.DataFrame:
    return pl.DataFrame(rows, schema=schema, strict=False)


# ── Daily port activity ───────────────────────────────────────────────────


def _parse_port_activity(features: list[dict[str, Any]]) -> pl.DataFrame:
    if not features:
        return pl.DataFrame()
    rows = _map_fields(features, _ACTIVITY_FIELDS)
    for row, feat in zip(rows, features, strict=True):
        row["activity_date"] = _to_date(feat.get("attributes", {}).get("date"))
    schema = {t: d for t, _, d in _ACTIVITY_FIELDS} | {"activity_date": pl.Date()}
    return _finish_activity(_frame(rows, schema).lazy()).collect()


def _read_activity_csv(path: Path) -> pl.LazyFrame:
    """Lazily read the Hub CSV export into the port_activity shape."""
    lf = pl.scan_csv(path, infer_schema=False, encoding="utf8-lossy")
    # Hub prefixes the file with a UTF-8 BOM, which can stick to the first name.
    first = lf.collect_schema().names()[0]
    if first != first.lstrip("\ufeff"):
        lf = lf.rename({first: first.lstrip("\ufeff")})
    return _finish_activity(
        lf.select(
            pl.col("date")
            .str.replace_all("/", "-")
            .str.slice(0, 10)
            .str.to_date("%Y-%m-%d", strict=False)
            .alias("activity_date"),
            *[pl.col(src).cast(dtype, strict=False).alias(t) for t, src, dtype in _ACTIVITY_FIELDS],
        )
    )


def _finish_activity(lf: pl.LazyFrame) -> pl.LazyFrame:
    """Drop undated/unkeyed rows and add the partition and lineage columns."""
    return lf.filter(
        pl.col("activity_date").is_not_null() & pl.col("port_id").is_not_null()
    ).with_columns(
        pl.col("activity_date").dt.year().cast(pl.Int32).alias("year"),
        pl.lit(SOURCE_ACTIVITY).alias("source"),
        pl.lit(date.today()).alias("partition_date"),
    )


def _download(url: str, dest: Path) -> None:
    with requests.get(url, stream=True, timeout=600) as resp:
        resp.raise_for_status()
        with dest.open("wb") as fh:
            for chunk in resp.iter_content(chunk_size=1 << 20):
                fh.write(chunk)


def _backfill_activity_from_csv() -> tuple[int, int]:
    """Load the full history from the Hub CSV, one year per write.

    Returns (rows_fetched, rows_written). The CSV (~1 GB) lives in a temp
    directory that is removed afterwards.
    """
    fetched = written = 0
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "daily_ports.csv"
        logger.info("Downloading PortWatch Daily_Ports_Data CSV export")
        _download(DAILY_PORTS_CSV_URL, path)
        lf = _read_activity_csv(path)
        years = sorted(lf.select(pl.col("year").unique()).collect()["year"].to_list())
        for year in years:
            chunk = lf.filter(pl.col("year") == year).collect()
            fetched += chunk.height
            written += write_raw(SOURCE_ACTIVITY, chunk, table_name="port_activity")
            logger.info("Backfilled %d port_activity rows for %d", chunk.height, year)
    return fetched, written


def _latest_activity_date() -> date | None:
    conn = get_connection()
    try:
        row = conn.execute(
            "SELECT max(activity_date) FROM port_activity WHERE source = ?",
            [SOURCE_ACTIVITY],
        ).fetchone()
    except duckdb.CatalogException:
        return None
    finally:
        conn.close()
    return row[0] if row else None


def collect_port_activity(
    tracker: SourceTracker | None = None,
    bulk_backfill: bool | None = None,
) -> int:
    """Collect daily port activity and write it to `port_activity`.

    An empty table is filled from the full CSV export when bulk backfill is
    allowed (CI), otherwise with the last `INITIAL_LOOKBACK_DAYS`. Every run
    then re-fetches the trailing `REVISION_WINDOW_DAYS` from the live layer.
    """
    if tracker is None:
        tracker = SourceTracker()
    if bulk_backfill is None:
        bulk_backfill = settings.allow_bulk_backfill

    with TimedCollector(tracker, SOURCE_ACTIVITY) as tc:
        latest = _latest_activity_date()
        if latest is None and bulk_backfill:
            tc.rows_fetched, tc.rows_written = _backfill_activity_from_csv()
            latest = _latest_activity_date()

        if latest is not None:
            start = latest - timedelta(days=REVISION_WINDOW_DAYS)
        else:
            start = date.today() - timedelta(days=INITIAL_LOOKBACK_DAYS)

        logger.info("Fetching PortWatch daily port activity since %s", start)
        features = query_all(DAILY_PORTS_URL, where=f"date >= DATE '{start.isoformat()}'")
        df = _parse_port_activity(features)
        tc.rows_fetched += df.height
        if df.height == 0:
            logger.warning("No PortWatch port activity returned since %s", start)
            return tc.rows_written

        tc.rows_written += write_raw(SOURCE_ACTIVITY, df, table_name="port_activity")
        return tc.rows_written


# ── Port reference data ───────────────────────────────────────────────────


def _parse_port_profiles(features: list[dict[str, Any]]) -> pl.DataFrame:
    if not features:
        return pl.DataFrame()
    df = _frame(_map_fields(features, _PROFILE_FIELDS), {t: d for t, _, d in _PROFILE_FIELDS})
    return df.filter(pl.col("port_id").is_not_null()).with_columns(
        pl.lit(SOURCE_PROFILES).alias("source")
    )


def collect_port_profiles(tracker: SourceTracker | None = None) -> int:
    """Collect the PortWatch port reference table into `port_profiles`."""
    if tracker is None:
        tracker = SourceTracker()
    with TimedCollector(tracker, SOURCE_PROFILES) as tc:
        df = _parse_port_profiles(query_all(PORTS_URL))
        tc.rows_fetched = df.height
        if df.height == 0:
            logger.warning("No PortWatch port profiles returned")
            return 0
        tc.rows_written = write_raw(SOURCE_PROFILES, df, table_name="port_profiles")
        return tc.rows_written


# ── Monthly trade nowcasts ────────────────────────────────────────────────


def _parse_tradenow(features: list[dict[str, Any]]) -> pl.DataFrame:
    if not features:
        return pl.DataFrame()
    rows = _map_fields(features, _TRADENOW_FIELDS)
    for row, feat in zip(rows, features, strict=True):
        row["month_date"] = _to_date(feat.get("attributes", {}).get("date"))
    schema = {t: d for t, _, d in _TRADENOW_FIELDS} | {"month_date": pl.Date()}
    return (
        _frame(rows, schema)
        .filter(pl.col("month_date").is_not_null() & pl.col("region").is_not_null())
        .with_columns(
            pl.lit(SOURCE_TRADENOW).alias("source"),
            pl.lit(date.today()).alias("partition_date"),
        )
    )


def collect_trade_nowcast(tracker: SourceTracker | None = None) -> int:
    """Collect PortWatch TradeNow monthly nowcasts into `trade_nowcast`.

    The full table is ~18k rows, and recent months are revised as data
    firms up, so every run re-fetches all of it.
    """
    if tracker is None:
        tracker = SourceTracker()
    with TimedCollector(tracker, SOURCE_TRADENOW) as tc:
        df = _parse_tradenow(query_all(TRADENOW_URL))
        tc.rows_fetched = df.height
        if df.height == 0:
            logger.warning("No PortWatch TradeNow data returned")
            return 0
        tc.rows_written = write_raw(SOURCE_TRADENOW, df, table_name="trade_nowcast")
        return tc.rows_written


# ── Disruption events ─────────────────────────────────────────────────────


def _parse_disruptions(features: list[dict[str, Any]]) -> pl.DataFrame:
    """PortWatch's curated disruptions: GDACS events matched to ports."""
    rows = []
    for feat in features:
        a = feat.get("attributes", {})
        if a.get("eventid") is None:
            continue
        rows.append({
            "event_id": str(a["eventid"]),
            "episode_id": None,
            "event_type": a.get("eventtype"),
            "event_name": a.get("eventname"),
            "description": _strip_html(a.get("htmldescription")),
            "alert_level": a.get("alertlevel"),
            "alert_score": None,
            "severity_text": a.get("severitytext"),
            "country": a.get("country"),
            "iso3": None,
            "affected_countries": None,
            "affected_ports": a.get("affectedports") or None,
            "n_affected_ports": a.get("n_affectedports"),
            "affected_population": a.get("affectedpopulation") or None,
            "is_current": None,
            "from_date": _to_datetime(a.get("fromdate")),
            "to_date": _to_datetime(a.get("todate")),
            "latitude": a.get("lat"),
            "longitude": a.get("long"),
        })
    return _finish_events(rows, SOURCE_DISRUPTIONS)


def _parse_geopulse(features: list[dict[str, Any]]) -> pl.DataFrame:
    """GeoPulse: GDACS event episodes with affected countries."""
    rows = []
    for feat in features:
        a = feat.get("attributes", {})
        if a.get("eventid") is None:
            continue
        geom = feat.get("geometry") or {}
        severity_text = None
        if a.get("severitydata"):
            try:
                severity_text = json.loads(a["severitydata"]).get("severitytext")
            except (TypeError, ValueError, AttributeError):
                severity_text = None
        is_current = a.get("iscurrent")
        rows.append({
            "event_id": str(a["eventid"]),
            "episode_id": None if a.get("episodeid") is None else str(a["episodeid"]),
            "event_type": a.get("eventtype"),
            "event_name": a.get("eventname") or a.get("name") or None,
            "description": a.get("description") or _strip_html(a.get("htmldescription")),
            "alert_level": a.get("alertlevel"),
            "alert_score": a.get("alertscore"),
            "severity_text": severity_text,
            "country": a.get("country"),
            "iso3": a.get("iso3"),
            "affected_countries": a.get("affectedcountries") or None,
            "affected_ports": None,
            "n_affected_ports": None,
            "affected_population": None,
            "is_current": None if is_current is None else bool(is_current),
            "from_date": _to_datetime(a.get("fromdate")),
            "to_date": _to_datetime(a.get("todate")),
            "latitude": geom.get("y"),
            "longitude": geom.get("x"),
        })
    return _finish_events(rows, SOURCE_GEOPULSE)


def _finish_events(rows: list[dict[str, Any]], source: str) -> pl.DataFrame:
    if not rows:
        return pl.DataFrame()
    return _frame(rows, _EVENT_SCHEMA).with_columns(
        pl.lit(source).alias("source"),
        pl.lit(date.today()).alias("partition_date"),
    )


def collect_disruption_events(tracker: SourceTracker | None = None) -> int:
    """Collect PortWatch disruptions and GeoPulse events into `disruption_events`."""
    if tracker is None:
        tracker = SourceTracker()
    with TimedCollector(tracker, SOURCE_DISRUPTIONS) as tc:
        frames = [
            (SOURCE_DISRUPTIONS, _parse_disruptions(query_all(DISRUPTIONS_URL))),
            (SOURCE_GEOPULSE, _parse_geopulse(query_all(GEOPULSE_URL, return_geometry=True))),
        ]
        for source, df in frames:
            tc.rows_fetched += df.height
            if df.height == 0:
                logger.warning("No %s events returned", source)
                continue
            tc.rows_written += write_raw(source, df, table_name="disruption_events")
        return tc.rows_written
